image: "rust:latest"

stages:
  - build
  - test

yubihsm-rs-build:
  stage: build
  script:
    - RUSTFLAGS=-Ctarget-feature=+aes cargo +nightly build

yubihsm-rs-test:
  stage: test
  script:
    - RUSTFLAGS=-Ctarget-feature=+aes cargo +nightly test --features=mockhsm