image: "rustlang/rust:nightly"

stages:
  - build
  - test

yubihsm-rs-build:
  stage: build
  script:
    - rustup install nightly
    - RUSTFLAGS=-Ctarget-feature=+aes cargo +nightly build

yubihsm-rs-test:
  stage: test
  script:
    - RUSTFLAGS=-Ctarget-feature=+aes cargo +nightly test --features=mockhsm