[package]
name          = "yubihsm"
description   = "Pure Rust client for YubiHSM2 devices"
version       = "0.13.0" # Also update html_root_url in lib.rs when bumping this
license       = "MIT OR Apache-2.0"
authors       = ["Tony Arcieri <tony@iqlusion.io>"]
documentation = "https://docs.rs/yubihsm"
homepage      = "https://github.com/tendermint/yubihsm-rs"
repository    = "https://github.com/tendermint/yubihsm-rs/tree/master/"
readme        = "README.md"
categories    = ["cryptography"]
keywords      = ["cryptography", "encryption", "security"]

[badges]
circle-ci = { repository = "tendermint/yubihsm-rs" }

[dependencies]
aes = "0.1"
bitflags = "1.0"
block-modes = "0.1"
byteorder = "1.2"
clear_on_drop = "0.2"
cmac = "0.1"
failure = "0.1"
failure_derive = "0.1"
hmac = { version = "0.6", optional = true }
pbkdf2 = { version = "0.2", optional = true }
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
ring = { version = "0.13", optional = true }
sha2 = { version = "0.7", optional = true }
subtle = "0.7"
untrusted = { version = "0.6", optional = true }
uuid = { version = "0.6", default-features = false }

[dev-dependencies]
lazy_static = "1"

[features]
aes-soft = ["aes/force_soft"]
default = ["passwords"]
integration = ["ring", "untrusted"]
mockhsm = ["integration", "passwords"]
nightly = ["clear_on_drop/nightly", "subtle/nightly"]
passwords = ["hmac", "pbkdf2", "sha2"]

[package.metadata.docs.rs]
features = ["mockhsm"]
rustc-args = ["-Ctarget-feature=+aes"]
