version: 2

jobs:
  build:
    docker:
      - image: iqlusion/rust-ci:20180626.0 # bump cache keys when modifying this

    steps:
      - checkout
      - restore_cache:
          key: cache-20180626.0 # bump save_cache key below too
      - run:
          name: rustfmt
          command: |
            cargo +$RUST_NIGHTLY_VERSION fmt --version
            cargo +$RUST_NIGHTLY_VERSION fmt -- --check
      - run:
          name: clippy
          command: |
            cargo +$RUST_NIGHTLY_VERSION clippy --version
            cargo +$RUST_NIGHTLY_VERSION clippy --features=mockhsm
      - run:
          name: build --no-default-features
          command: |
            rustc --version
            cargo --version
            cargo build --no-default-features
            cargo build --no-default-features --release
      - run:
          name: build
          command: |
            rustc --version
            cargo --version
            cargo build
            cargo build --release
      - run:
          name: test
          command: |
            rustc --version
            cargo --version
            cargo test --features=mockhsm
      - save_cache:
          key: cache-20180626.0 # bump restore_cache key above too
          paths:
            - "~/.cargo"
            - "./target"
